AppBundle\Entity\Set:
    type: entity
    table: cardset
    repositoryClass: AppBundle\Repository\SetRepository
    gedmo:
        translation:
            locale: locale
    manyToOne:
        cycle:
            targetEntity: Cycle
            inversedBy: sets
            joinColumn:
                name: cycle_id
                referencedColumnName: id
    oneToMany:
        cards:
            targetEntity: Card
            orderBy: {'position':'ASC'}
            mappedBy: set
        starterPacks:
            targetEntity: StarterPack
            orderBy: {'code': 'ASC'}
            mappedBy: set
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        projectName:
            type: string
            length: 50
            nullable: true
            column: project_name
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
        position:
            type: smallint
            nullable: false
        size:
            type: smallint
            nullable: false,
        cgdbIdStart:
            type: smallint
            nullable: false,
            column: cgdb_id_start
        cgdbIdEnd:
            type: smallint
            nullable: false,
            column: cgdb_id_end
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        dateRelease:
            type: date
            nullable: true
            column: date_release
    uniqueConstraints:
        pack_code_idx:
            columns: [ code ]
